<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { AlertTriangle, ArrowRight, BookOpenCheck, Check, CheckCircle2, ChevronRight, Download, FilePenLine, FileSearch, GitCompareArrows, GraduationCap, History, LoaderCircle, MessageCircle, RefreshCw, ShieldCheck, Target, ThumbsUp, TriangleAlert } from 'lucide-vue-next'
import AppChrome from '@/shared/ui/AppChrome.vue'
import AppDrawer from '@/shared/ui/AppDrawer.vue'
import AppModal from '@/shared/ui/AppModal.vue'
import AppSelect from '@/shared/ui/AppSelect.vue'
import AppTag from '@/shared/ui/AppTag.vue'
import { useToastFeedback } from '@/shared/ui/toast'
import { errorMessage } from '@/shared/api/types'
import { compareMatchReportVersions, createReportExport, createResumeOptimization, downloadReportExport, fetchJobMatch, fetchMatchReport, fetchMatchReportVersions, updateImprovement } from '../services/jobMatchApi'
import type { ImprovementTask, JobMatch, JobMatchClaim, JobMatchReport, JobMatchReportComparison, JobMatchReportVersion } from '../types'
import { displayJobMatchText, jobMatchDisplayLabels, jobMatchStatusTone } from '../utils/reportPresentation'
import { clampMatchScore, JOB_MATCH_REPORT_TABS, reportTabFromQuery, type JobMatchReportTab } from '../utils/uiPresentation'
import '../job-match.css'

const route=useRoute();const router=useRouter();const match=ref<JobMatch|null>(null);const report=ref<JobMatchReport|null>(null)
const loading=ref(true);const pending=ref(false);const pageError=ref('');const activeTab=ref<JobMatchReportTab>('overview');const evidenceOpen=ref(false);const exportOpen=ref(false);const versionsOpen=ref(false);const versions=ref<JobMatchReportVersion[]>([]);const comparison=ref<JobMatchReportComparison|null>(null);const compareFrom=ref(0);const compareTo=ref(0);const selectedClaim=ref<JobMatchClaim|null>(null);const exportFormat=ref('PDF')
useToastFeedback(pageError,'error','job-match-report-error')
const tabs=JOB_MATCH_REPORT_TABS
const dimensions=computed(()=>report.value?.report.dimensions??{})
const matchScore=computed(()=>clampMatchScore(report.value?.report.score))
const dimensionItems=computed(()=>[
  ['hardGate','硬性资格',report.value?.report.hardGatePassed?100:0],['coreSkills','核心技能',dimensions.value.coreSkills??0],['experience','经历相关度',dimensions.value.experience??0],['evidence','证据强度',dimensions.value.evidence??0],['resumeExpression','简历表达',dimensions.value.resumeExpression??0],['growthCost','成长成本',dimensions.value.growthCost??0],
] as Array<[string,string,number]>)
const strengths=computed(()=>report.value?.report.ai?.strengths??report.value?.report.ruleStrengths??[])
const gaps=computed(()=>report.value?.report.ai?.gaps??report.value?.report.ruleGaps??[])
const matrix=computed(()=>report.value?.report.ai?.evidenceMatrix??report.value?.report.requirements??[])
const recommendation=computed(()=>report.value?.report.ai?.recommendation)
const requirementsById=computed(()=>new Map((report.value?.report.requirements??[]).map(item=>[String(item.requirementId??''),item])))
const selectedRequirementTitle=computed(()=>{const requirement=requirementsById.value.get(String(selectedClaim.value?.requirementId??''));return requirement?optionalStr(requirement,'text'):(selectedClaim.value?'未找到对应岗位要求':'请选择一项结论')})
const nextActions=computed(()=>[
  {title:'优化简历中的项目成果',desc:'把已有事实转成更贴合 JD 的字段级表达。'},
  {title:gaps.value.length?`优先处理 ${gaps.value.length} 项关键缺口`:'补充可验证证据',desc:'区分能力、证据与表达缺口，避免无效学习。'},
  {title:'按岗位主题准备模拟面试',desc:'围绕优势、缺口和高风险追问进行训练。'},
])
const displayText=displayJobMatchText
function optionalStr(item:Record<string,unknown>,...keys:string[]){for(const key of keys){const value=item[key];if(typeof value==='string'&&value.trim())return displayText(value)}return ''}
function str(item:Record<string,unknown>,...keys:string[]){return optionalStr(item,...keys)||'待补充说明'}
function reportItemTitle(item:Record<string,unknown>){const direct=optionalStr(item,'title','text');if(direct)return direct;const requirement=requirementsById.value.get(String(item.requirementId??''));const requirementText=requirement?optionalStr(requirement,'text'):'';if(requirementText)return requirementText;return jobMatchDisplayLabels[String(item.type??'')]??'待补充说明'}
function num(item:Record<string,unknown>,key:string,fallback=0){const value=item[key];return typeof value==='number'?value:fallback}
function list(item:Record<string,unknown>,key:string){return Array.isArray(item[key])?item[key] as unknown[]:[]}
function matrixList(item:Record<string,unknown>,key:string){const direct=list(item,key);if(direct.length)return direct;const requirement=requirementsById.value.get(String(item.requirementId??''));return requirement?list(requirement,key):[]}
function matrixStatus(item:Record<string,unknown>){const direct=optionalStr(item,'status','factStatus');if(direct)return direct;const requirement=requirementsById.value.get(String(item.requirementId??''));return requirement?str(requirement,'status','factStatus'):'待补充说明'}
function matrixRawStatus(item:Record<string,unknown>){const direct=item.status??item.factStatus;if(typeof direct==='string')return direct;const requirement=requirementsById.value.get(String(item.requirementId??''));return requirement?.status??requirement?.factStatus}
async function setActiveTab(tab:JobMatchReportTab, focusContent=false){activeTab.value=tab;await router.replace({query:{...route.query,tab:tab==='overview'?undefined:tab}});if(focusContent){await nextTick();document.querySelector<HTMLElement>('.jm-report-content [data-report-heading]')?.focus()}}
function onReportTabKeydown(event:KeyboardEvent,current:JobMatchReportTab){const index=tabs.findIndex(tab=>tab.id===current);let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();const tab=tabs[next];void setActiveTab(tab.id);(event.currentTarget as HTMLElement).parentElement?.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next]?.focus()}
function openClaim(claim?:JobMatchClaim){selectedClaim.value=claim??report.value?.claims[0]??null;evidenceOpen.value=true}
async function optimize(){if(!match.value)return;pending.value=true;try{const link=await createResumeOptimization(match.value.id,match.value.version);await router.push(link.path)}catch(reason){pageError.value=errorMessage(reason,'简历优化会话创建失败')}finally{pending.value=false}}
async function exportReport(){if(!match.value)return;pending.value=true;pageError.value='';try{const created=await createReportExport(match.value.id,exportFormat.value,match.value.version);if(created.status==='COMPLETED'){const downloaded=await downloadReportExport(created.id);const url=URL.createObjectURL(downloaded.blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=downloaded.filename||`JobProof-岗位匹配报告.${exportFormat.value.toLowerCase()}`;anchor.click();URL.revokeObjectURL(url)}else{pageError.value='报告导出任务已创建，完成后可在历史记录中下载。'}exportOpen.value=false}catch(reason){pageError.value=errorMessage(reason,'报告导出失败')}finally{pending.value=false}}
async function setTask(task:ImprovementTask,status:string){if(!match.value)return;try{const updated=await updateImprovement(match.value.id,task.id,status,task.version);const index=report.value?.learningPlan.findIndex(item=>item.id===task.id)??-1;if(report.value&&index>=0)report.value.learningPlan[index]=updated}catch(reason){pageError.value=errorMessage(reason,'学习任务更新失败')}}
async function openVersions(){versionsOpen.value=true;comparison.value=null;if(versions.value.length>1){compareFrom.value=versions.value[1].version;compareTo.value=versions.value[0].version;await compareVersions()}}
async function compareVersions(){if(!match.value||!compareFrom.value||!compareTo.value)return;pending.value=true;try{comparison.value=await compareMatchReportVersions(match.value.id,compareFrom.value,compareTo.value)}catch(reason){pageError.value=errorMessage(reason,'报告版本比较失败')}finally{pending.value=false}}
async function load(){try{[match.value,report.value,versions.value]=await Promise.all([fetchJobMatch(String(route.params.id)),fetchMatchReport(String(route.params.id)),fetchMatchReportVersions(String(route.params.id))]);activeTab.value=reportTabFromQuery(route.query.tab)}catch(reason){pageError.value=errorMessage(reason,'岗位匹配报告读取失败')}finally{loading.value=false}}
onMounted(load)
</script>

<template><AppChrome><main class="jm-page"><div class="jm-shell">
  <section v-if="loading" class="jm-card jm-loading"><LoaderCircle class="jm-spin" :size="20" /> 正在读取岗位匹配报告</section>
<template v-else><header class="jm-report-head"><div class="jm-report-head__top"><div class="jm-report-title"><h1>岗位匹配报告</h1><p><strong>{{ match?.title }}<template v-if="match?.company"> · {{ match.company }}</template></strong><AppTag :tone="match?.status==='COMPLETED'?'green':'orange'">{{ match?.status==='COMPLETED'?'分析完成':'历史报告可用' }}</AppTag><AppTag tone="green">可信度 {{ report?.report.confidence ?? 0 }}%</AppTag><AppTag tone="gray">{{ report?.updatedAt ? new Date(report.updatedAt).toLocaleDateString('zh-CN') : '' }}</AppTag></p></div><div class="jm-report-actions"><button class="jm-secondary" type="button" aria-label="重新分析" @click="router.push({name:'job-match-new',query:{id:match?.id}})"><RefreshCw :size="16" /><span>重新分析</span></button><button class="jm-secondary" type="button" aria-label="版本记录" @click="openVersions"><History :size="16" /><span>版本</span></button><button class="jm-secondary" type="button" aria-label="导出报告" @click="exportOpen=true"><Download :size="16" /><span>导出报告</span></button><button class="jm-primary" type="button" :disabled="pending" @click="optimize"><FilePenLine :size="16" />优化简历</button></div></div><nav class="jm-tabs" role="tablist" aria-label="报告视图"><button v-for="tab in tabs" :id="`jm-report-tab-${tab.id}`" :key="tab.id" type="button" role="tab" :aria-selected="activeTab===tab.id" :aria-controls="`jm-report-panel-${tab.id}`" :tabindex="activeTab===tab.id?0:-1" :class="{ 'is-active':activeTab===tab.id }" @click="setActiveTab(tab.id)" @keydown="onReportTabKeydown($event,tab.id)">{{ tab.label }}</button></nav></header>
  <Transition name="jm-report-switch" mode="out-in"><div :id="`jm-report-panel-${activeTab}`" :key="activeTab" class="jm-report-content" role="tabpanel" :aria-labelledby="`jm-report-tab-${activeTab}`">
  <template v-if="activeTab==='overview'">
    <section class="jm-card jm-report-overview"><div class="jm-report-score"><div class="jm-score-large" :style="{ '--score': `${matchScore}%` }"><p><strong><span class="jm-score-value">{{ matchScore }}</span><small>%</small></strong><span class="jm-score-label">综合匹配度</span></p></div></div><div class="jm-recommendation"><h3>匹配结论</h3><strong><ThumbsUp :size="16" />{{ recommendation?.code==='RECOMMENDED'?'推荐投递':recommendation?.code==='CAUTION'?'谨慎评估':'准备后投递' }}</strong><p>{{ displayText(recommendation?.rationale || '规则结果与 AI 语义分析已完成，请按缺口优先级准备。') }}</p></div><article v-for="item in dimensionItems" :key="item[0]" class="jm-dimension"><small>{{ item[1] }}</small><strong>{{ clampMatchScore(item[2]) }}</strong><i :style="{ '--score': `${clampMatchScore(item[2])}%` }" /></article></section>
    <section class="jm-overview-grid"><article class="jm-card jm-report-panel"><h2>硬性条件</h2><div class="jm-list"><div v-for="(item,index) in (report?.report.ai?.hardGates ?? report?.report.requirements?.filter(value=>value.hardGate))" :key="index" class="jm-list__row"><span><Check :size="16" /></span><p><strong>{{ reportItemTitle(item) }}</strong><small>{{ str(item,'explanation','status') }}</small></p><AppTag :tone="report?.report.hardGatePassed?'green':'orange'">{{ report?.report.hardGatePassed?'通过':'待核实' }}</AppTag></div><div v-if="!(report?.report.ai?.hardGates?.length || report?.report.requirements?.some(value=>value.hardGate))" class="jm-list__row"><span><ShieldCheck :size="16" /></span><p><strong>JD 未识别出独立硬性门槛</strong><small>这不代表岗位没有要求，请结合原文确认。</small></p></div></div></article>
    <article class="jm-card jm-report-panel"><h2>关键结论</h2><div class="jm-conclusion-list"><button class="jm-conclusion-item is-strength" type="button" @click="setActiveTab('strengths',true)"><span><ThumbsUp :size="17" /></span><p><strong>{{ strengths.length }} 项匹配优势</strong><small>已在简历或授权资料中找到可追溯证据</small></p><ChevronRight :size="18" /></button><button class="jm-conclusion-item is-gap" type="button" @click="setActiveTab('gaps',true)"><span><TriangleAlert :size="17" /></span><p><strong>{{ gaps.length }} 项需要处理</strong><small>能力、证据、表达与客观限制分别处理</small></p><ChevronRight :size="18" /></button><button class="jm-conclusion-item is-evidence" type="button" @click="setActiveTab('evidence',true)"><span><FileSearch :size="17" /></span><p><strong>{{ report?.claims.length ?? 0 }} 项可溯源结论</strong><small>逐条查看 JD、简历和资料库引用</small></p><ChevronRight :size="18" /></button></div></article>
    <article class="jm-card jm-report-panel"><h2>下一步建议</h2><div class="jm-list"><div v-for="(item,index) in nextActions" :key="item.title" class="jm-list__row"><span style="color:#fff;background:#2463eb">{{ index+1 }}</span><p><strong>{{ item.title }}</strong><small>{{ item.desc }}</small></p></div></div><button class="jm-primary jm-report-cta" type="button" @click="optimize"><FilePenLine :size="16" />开始优化简历</button><button class="jm-secondary jm-report-cta" type="button" @click="router.push({name:'mock-interview-create',query:{jobMatchId:match?.id}})"><MessageCircle :size="16" />生成模拟面试</button></article></section>
    <div class="jm-privacy"><FileSearch :size="18" /><p><strong>每项结论均可查看证据来源</strong><span>点击卡片或证据覆盖标签，查看 JD 原文定位、简历字段与授权资料。</span></p><button class="jm-secondary" type="button" @click="openClaim()">了解证据来源 <ArrowRight :size="15" /></button></div>
  </template>
  <section v-else class="jm-card jm-report-body"><header class="jm-report-body__head"><div><h2 data-report-heading tabindex="-1">{{ tabs.find(item=>item.id===activeTab)?.label }}</h2><p>{{ activeTab==='strengths'?'确认哪些能力已经被事实支撑':activeTab==='gaps'?'区分真正能力缺口与材料表达问题':activeTab==='evidence'?'逐条查看岗位要求、简历和资料证据':'将确认的能力缺口拆成可验收任务' }}</p></div><button v-if="activeTab==='gaps'" class="jm-secondary" type="button" @click="router.push({name:'job-match-similar',params:{id:match?.id}})"><Target :size="16" />查看相似方向</button></header>
    <div v-if="activeTab==='strengths'" class="jm-detail-list"><article v-for="(item,index) in strengths" :key="index" class="jm-detail-item"><span><CheckCircle2 :size="19" /></span><div><h3>{{ str(item,'title','text') }}</h3><p>{{ str(item,'explanation','reasoning','status') }}</p><div class="jm-chip-row"><span v-for="source in list(item,'evidenceIds')" :key="String(source)" class="jm-chip">证据 {{ String(source).slice(0,8) }}</span></div></div><aside><AppTag tone="green">{{ num(item,'score',80) }} 分</AppTag><button class="jm-text-btn" type="button" @click="openClaim(report?.claims[index])">溯源</button></aside></article><div v-if="!strengths.length" class="jm-empty"><div><span><FileSearch :size="30" /></span><h3>暂无足够的强证据优势</h3><p>这不代表没有能力，建议在证据覆盖中查看尚待补充的材料。</p></div></div></div>
    <div v-else-if="activeTab==='gaps'" class="jm-detail-list"><article v-for="(item,index) in gaps" :key="index" class="jm-detail-item"><span style="color:#e4750c;background:#fff1df"><AlertTriangle :size="19" /></span><div><h3>{{ reportItemTitle(item) }}</h3><p>{{ str(item,'impact','explanation','status') }}</p><div class="jm-chip-row"><span class="jm-chip">{{ str(item,'type') }}</span><span class="jm-chip">{{ str(item,'priority') }}</span><span class="jm-chip">{{ str(item,'estimatedTime') }}</span></div></div><aside><button class="jm-text-btn" type="button" @click="openClaim(report?.claims.find(claim=>claim.requirementId===item.requirementId))">查看依据</button></aside></article></div>
    <div v-else-if="activeTab==='evidence'" class="jm-history-table-wrap"><table class="jm-matrix"><thead><tr><th>岗位要求</th><th>简历证据</th><th>资料库证据</th><th>事实状态</th><th>可信度</th><th></th></tr></thead><tbody><tr v-for="(item,index) in matrix" :key="index"><td>{{ reportItemTitle(item) }}</td><td>{{ matrixList(item,'resumeRefs').length?`${matrixList(item,'resumeRefs').length} 处简历引用`:'暂未发现证据' }}</td><td>{{ matrixList(item,'evidenceIds').length?`${matrixList(item,'evidenceIds').length} 项授权证据`:'未授权或未发现' }}</td><td><AppTag :tone="jobMatchStatusTone(matrixRawStatus(item))">{{ matrixStatus(item) }}</AppTag></td><td>{{ num(item,'confidence',report?.report.confidence??0) }}%</td><td><button class="jm-text-btn" type="button" @click="openClaim(report?.claims.find(claim=>claim.requirementId===item.requirementId))">溯源</button></td></tr></tbody></table></div>
    <div v-else class="jm-detail-list"><article v-for="task in report?.learningPlan" :key="task.id" class="jm-detail-item"><span style="color:#7745e4;background:#f2edff"><GraduationCap :size="19" /></span><div><h3>{{ task.title }}</h3><p>{{ task.task }}</p><div class="jm-source-block"><strong>产物</strong><small>{{ task.expectedOutput }}</small><strong>验收标准</strong><small>{{ task.acceptanceCriteria }}</small></div><div class="jm-chip-row"><span class="jm-chip">{{ task.estimatedHours }} 小时</span><span class="jm-chip">{{ displayText(task.phase) }}</span><span class="jm-chip">{{ displayText(task.priority) }}</span></div></div><aside><button v-if="task.status!=='DONE'" class="jm-secondary" type="button" @click="setTask(task,'DONE')"><Check :size="15" />完成</button><AppTag v-else tone="green">已完成</AppTag></aside></article><div v-if="!report?.learningPlan.length" class="jm-empty"><div><span><BookOpenCheck :size="30" /></span><h3>没有需要生成的能力学习任务</h3><p>学习计划只针对已确认的能力缺口，不会为证据不足项虚构任务。</p></div></div></div>
  </section>
  </div></Transition>
  <AppDrawer :open="evidenceOpen" title="结论与证据溯源" :width="500" @close="evidenceOpen=false"><div class="jm-evidence-drawer-content"><section class="jm-source-block"><AppTag tone="blue">岗位要求</AppTag><h3>{{ selectedRequirementTitle }}</h3><small>结论类型：{{ displayText(selectedClaim?.conclusionType || '—') }} · 可信度 {{ selectedClaim?.confidence ?? report?.report.confidence ?? 0 }}%</small><small v-if="selectedClaim?.requirementId">原文定位：JD 条目 {{ selectedClaim.requirementId.slice(0,8) }}</small></section><section class="jm-source-block"><AppTag tone="green">分析理由</AppTag><small>{{ displayText(selectedClaim?.reasoning || '报告中的规则结果与 AI 解释会在此展示。') }}</small></section><section class="jm-source-block"><AppTag tone="purple">授权证据</AppTag><div class="jm-chip-row" style="margin-top:8px"><span v-for="evidence in selectedClaim?.evidenceIds" :key="evidence" class="jm-chip">{{ evidence }}</span><small v-if="!selectedClaim?.evidenceIds.length">当前结论没有引用资料库文件。</small></div></section><div class="jm-privacy"><ShieldCheck :size="17" /><span>技能标签不会被当作强证据；联系方式和敏感字段已从模型输入排除。</span></div></div></AppDrawer>
  <AppModal :open="versionsOpen" title="报告版本与变化" @close="versionsOpen=false"><div class="jm-version-dialog"><div v-if="versions.length>1" class="jm-version-selectors"><label>较早版本<AppSelect v-model="compareFrom" @change="compareVersions"><option v-for="item in versions" :key="item.id" :value="item.version">版本 {{ item.version }} · {{ new Date(item.createdAt).toLocaleString('zh-CN') }}</option></AppSelect></label><GitCompareArrows :size="20" /><label>较新版本<AppSelect v-model="compareTo" @change="compareVersions"><option v-for="item in versions" :key="item.id" :value="item.version">版本 {{ item.version }} · {{ new Date(item.createdAt).toLocaleString('zh-CN') }}</option></AppSelect></label></div><div v-if="pending" class="jm-loading"><LoaderCircle class="jm-spin" :size="18" /> 正在比较版本</div><div v-else-if="comparison" class="jm-version-deltas"><div v-for="item in comparison.changes" :key="item.label"><span>{{ item.label }}</span><strong>{{ item.before }} → {{ item.after }}</strong><AppTag :tone="item.delta>0?'green':item.delta<0?'orange':'gray'">{{ item.delta>0?'+':'' }}{{ item.delta }}</AppTag></div></div><div v-else class="jm-empty jm-version-empty"><div><span><History :size="28" /></span><h3>{{ versions.length===1?'当前只有一个报告版本':'暂无可比较版本' }}</h3><p>回答澄清问题或重新分析后，新结果会作为不可变版本保存。</p></div></div></div></AppModal>
  <AppModal :open="exportOpen" title="导出岗位匹配报告" @close="exportOpen=false"><div class="jm-export-options"><label v-for="format in ['PDF','DOCX','JSON']" :key="format" class="jm-export-option"><input v-model="exportFormat" type="radio" :value="format"><span><strong>{{ format }}</strong><small>{{ format==='PDF'?'主要验收格式，适合分享与打印':format==='DOCX'?'可在 Word/WPS 中打开':'结构化数据，适合归档与系统对接' }}</small></span></label><div class="jm-privacy"><ShieldCheck :size="17" /><span>默认隐藏联系方式和个人资料，导出文件使用限时下载。</span></div></div><template #footer><button class="jm-secondary" type="button" @click="exportOpen=false">取消</button><button class="jm-primary" type="button" :disabled="pending" @click="exportReport"><LoaderCircle v-if="pending" class="jm-spin" :size="16" /><Download v-else :size="16" />生成 {{ exportFormat }}</button></template></AppModal>
</template>
</div></main></AppChrome></template>
