package com.jobproof.modules.resume.application;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jobproof.modules.resume.domain.ResumeTemplateManifest;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * The built-in templates shipped with this build (templates/builtin-manifests.json, generated by
 * frontend/scripts/export-template-manifests.mjs) and the mapping from the retired v3 drafts.
 */
@Component
public class BuiltInTemplateCatalog {
    public static final String RESOURCE = "templates/builtin-manifests.json";
    public static final String MANIFEST_SCHEMA = "resume-template-manifests-v1";

    /** Retired resume-layout-v3 drafts → the built-in template that replaces them (docs/phase2/03 §8). */
    public static final Map<String, String> LEGACY_TEMPLATES = Map.ofEntries(
            Map.entry("rlt-b-ats-minimal-v1", "clarity"),
            Map.entry("rlt-b-english-single-v1", "harvard"),
            Map.entry("rlt-b-cn-table-v1", "classic"),
            Map.entry("rlt-b-consulting-v1", "classic"),
            Map.entry("rlt-b-product-ops-v1", "ledger"),
            Map.entry("rlt-b-tech-single-v1", "engineer"),
            Map.entry("rlt-b-tech-double-v1", "engineer"),
            Map.entry("rlt-b-qa-data-v1", "engineer"),
            Map.entry("rlt-b-education-research-v1", "academic"),
            Map.entry("rlt-b-campus-v1", "campus"),
            Map.entry("rlt-b-career-pro-v1", "meridian"),
            Map.entry("rlt-b-finance-v1", "banker"));
    /** Codes older clients still send when creating a resume. */
    private static final Map<String, String> LEGACY_CODES = Map.of(
            "ATS", "clarity", "TECH", "engineer", "TABLE", "classic");
    private static final Set<String> STUDENT_IDENTITIES = Set.of("STUDENT", "GRADUATE");

    private final Map<String, Entry> byId;
    private final List<Entry> ordered;

    public BuiltInTemplateCatalog(ObjectMapper mapper) {
        JsonNode root;
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(RESOURCE)) {
            if (input == null) throw new IllegalStateException("Missing built-in template manifests: " + RESOURCE);
            root = mapper.readTree(input);
        } catch (IOException exception) {
            throw new IllegalStateException("Built-in template manifests are unreadable", exception);
        }
        if (!MANIFEST_SCHEMA.equals(root.path("schema").asText())) {
            throw new IllegalStateException("Unsupported built-in template manifest schema");
        }
        Map<String, Entry> entries = new LinkedHashMap<>();
        List<Entry> list = new ArrayList<>();
        int position = 0;
        for (JsonNode node : root.path("templates")) {
            ResumeTemplateManifest manifest = ResumeTemplateManifest.parse(mapper, node);
            Entry entry = new Entry(manifest, node, (position + 1) * 10);
            if (entries.putIfAbsent(manifest.id(), entry) != null) {
                throw new IllegalStateException("Duplicate built-in template id: " + manifest.id());
            }
            list.add(entry);
            position++;
        }
        if (list.isEmpty()) throw new IllegalStateException("No built-in templates found");
        LEGACY_TEMPLATES.values().forEach(id -> {
            if (!entries.containsKey(id)) throw new IllegalStateException("Legacy mapping targets unknown template " + id);
        });
        this.byId = Map.copyOf(entries);
        this.ordered = List.copyOf(list);
    }

    public List<Entry> all() {
        return ordered;
    }

    public List<String> ids() {
        return ordered.stream().map(entry -> entry.manifest().id()).toList();
    }

    public boolean contains(String templateId) {
        return templateId != null && byId.containsKey(templateId);
    }

    public Optional<Entry> find(String templateId) {
        return Optional.ofNullable(templateId == null ? null : byId.get(templateId));
    }

    /** Template id from a selector: a built-in id, a retired v3 id or a legacy code. */
    public Optional<String> resolve(String selector) {
        String value = selector == null ? "" : selector.trim();
        if (byId.containsKey(value)) return Optional.of(value);
        String legacy = LEGACY_TEMPLATES.get(value);
        if (legacy == null) legacy = LEGACY_CODES.get(value.toUpperCase(Locale.ROOT));
        return Optional.ofNullable(legacy);
    }

    public String defaultTemplateId(String identityType) {
        String preferred = identityType != null && STUDENT_IDENTITIES.contains(identityType) ? "campus" : "meridian";
        return byId.containsKey(preferred) ? preferred : ordered.get(0).manifest().id();
    }

    public record Entry(ResumeTemplateManifest manifest, JsonNode json, int sortOrder) {}
}
